//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : cs_bloodstrike_cz
//
// Download @: http://dwl.17buddies.net/link/map/12409/cs_bloodstrike_cz.html
//
//////////////////////////////////////////////////////////
maps\cs_bloodstrike_cz_detail.txt