gfx/env/lakecsgo_up.tga
gfx/env/lakecsgo_dn.tga
gfx/env/lakecsgo_lf.tga
gfx/env/lakecsgo_rt.tga
gfx/env/lakecsgo_ft.tga
gfx/env/lakecsgo_bk.tga
sprites/2dprops/lamp_spr.spr
sprites/de_nust2/glow.spr
models/costabrava/gins_leafy.mdl
sound/doors/wood_open.wav
models/safehouse/hessi_baum_edited.mdl
models/safehouse/hessi_big_baum.mdl
models/props_bank/bush02.mdl
models/cs_militia_csgo/militiarock03.mdl
models/props_lake/dock01_polecluster01d_256.mdl
models/props/rib.mdl
models/props_lake/swimming_buoy001a.mdl
models/props_lake/barstool01.mdl
models/props_lake/semi_flush_002.mdl
models/props_lake/stealthboat.mdl
models/props_militia/shelves_wood_opt.mdl
models/props_lake/drafting_optimize.mdl
models/props/car_hatchback.mdl
models/safehouse/lightfixture03_off.mdl
models/safehouse/scar_pillow.mdl
models/safehouse/towel_shhc_001.mdl
models/safehouse/rakovina.mdl
models/safehouse/scar_toiletbwl.mdl
models/props_lake/donut.mdl
models/props_lake/3dm_poolout_w.mdl
models/props_lake/scrapyarddumpster.mdl
models/props_lake/boat002.mdl
models/props_lake/cattlegate2.mdl
models/zp_models/zp_light/zp_light01.mdl
models/props_lake/loader.mdl
sound/ambient/wind/birdambiencedq.wav
sound/ambient/wind/tree_sway_wind_lp_02.wav
sound/ambient/wind/tree_sway_wind_lp_03.wav
sound/de_dockland/mer.wav
sound/ambient/wind/boathouse_boat_int_amb.wav
models/zp_models/zp_light/zp_light05.mdl
models/props_lake/cart_utility.mdl
models/safehouse/clothes.mdl
models/safehouse/couch_fabric-wreck.mdl
sprites/de_house/offpd.spr
sprites/de_house/mirror001.spr
sprites/buzz/buzz_kt_trava3.spr
sprites/buzz/buzz_kt_trava2.spr
sprites/2dprops/tube.spr
sprites/de_lakehouse/rug_green01.spr
sprites/de_lakehouse/papper1.spr
sprites/de_lakehouse/decalrug003a.spr
sprites/de_lakehouse/art_pix.spr
sprites/de_lakehouse/spanner.spr
sprites/de_lakehouse/rug001a_dark.spr
sprites/de_lakehouse/painting_p.spr


// maps/de_lake_csgo.nav
// maps/de_lake_csgo.res