de_nifan_LG.wad
models/de_nifan/nf_banana_d.mdl
models/de_nifan/nf_banana_x.mdl
models/de_nifan/nf_banana_z.mdl
models/de_nifan/nf_butterfly.mdl
models/de_nifan/nf_cat_lick.mdl
models/de_nifan/nf_ointy88_32.mdl
models/de_nifan/nf_pz01.mdl
models/de_nifan/nf_qarc_fern.mdl
models/de_nifan/nf_snake.mdl
models/de_nifan/nf_tree15.mdl
models/de_nifan/nf_unplant1.mdl
models/de_nifan/nf_zushu.mdl
sound/nifan/1buguniao.wav
sound/nifan/3mz.wav
sound/nifan/9zhu.wav
sound/nifan/dagou.wav
sound/nifan/eee.wav
sound/nifan/jichang.wav
sound/nifan/jiti2.wav
sound/nifan/jiti.wav
sound/nifan/muji3.wav
sound/nifan/muji.wav
sound/nifan/xiaogou3.wav
sound/nifan/ya2.wav
sound/nifan/zsj.wav
overviews/de_nifan.txt
overviews/de_nifan.bmp
maps/de_nifan.txt
maps/de_nifan.res

