chateau.wad
cs_747.wad
cs_bdog.wad
cs_cbble.wad
cs_havana.wad
cstrike.wad
de_airstrip.wad
de_aztec.wad
de_piranesi.wad
de_storm.wad
gfx/env/nowhere_night_bk.tga
gfx/env/nowhere_night_dn.tga
gfx/env/nowhere_night_ft.tga
gfx/env/nowhere_night_lf.tga
gfx/env/nowhere_night_rt.tga
gfx/env/nowhere_night_up.tga
halflife.wad
itsitaly.wad
maps/de_waypass.bsp
maps/de_waypass.res
maps/de_waypass.txt
models/bigtree.mdl
models/bluecar.mdl
models/bush.mdl
models/bush1.mdl
models/can.mdl
models/lv_bottle.mdl
models/russka_tree_noleaves.mdl
models/xen_trashcan.mdl
torntextures.wad
